#thank you @freifunk-darmstadt for publishing https://github.com/freifunk-darmstadt/ffda-peers/blob/master/.travis.yml

language: c
sudo: required

before_install:
 - sudo apt-get install dpkg-dev
 - mkdir /tmp/fastd-repo/
 - wget -O/tmp/fastd-repo/libsodium13_1.0.3-1~wheezy0_i386.deb http://freifunk-pirmasens.de/libsodium13_1.0.3-1~wheezy0_i386.deb
 - wget -O/tmp/fastd-repo/libuecc0_6-0uf1_i386.deb http://freifunk-pirmasens.de/libuecc0_6-0uf1_i386.deb
 - wget -O/tmp/fastd-repo/fastd_17-4_i386.deb http://freifunk-pirmasens.de/fastd_17-4_i386.deb
 - cd /tmp/fastd-repo/ && dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
 - echo "deb file:/tmp/fastd-repo/ ./" | sudo tee -a /etc/apt/sources.list.d/fastd.list
 - sudo apt-get install fastd

script:
 - for f in * ; do echo "checking $f..."; fastd --verify-config --config-peer $f || exit 1; done
 - grep --no-filename "key" * | egrep -o "[0-9a-f]{60,80}" | sort | uniq -d > /tmp/peers-dubchecker
 - if [ -s /tmp/peers-dubchecker ]; then
     echo -e '\x1b[31mfound duplicate keys:\x1b[0m';
     cat /tmp/peers-dubchecker | while read i; do
       echo -n "$i (";
       grep -F "$i" -l -r . | egrep -o "[-_0-9a-zA-Z]{0,80}" | while read node; do
         echo -n "$node, ";
       done | head -c -2;
       echo ")";
     done;
     exit 1;
   else
     echo -e '\x1b[32mfound no duplicate keys\x1b[0m';
   fi

notifications:
  irc:
    channels:
      - "irc.hackint.org#ffwp"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
