#thank you @freifunk-darmstadt for publishing https://github.com/freifunk-darmstadt/ffda-peers/blob/master/.travis.yml

language: c

before_install:
 - wget -O/tmp/libsodium13_1.0.3-1~wheezy0_i386.deb http://freifunk-pirmasens.de/libsodium13_1.0.3-1~wheezy0_i386.deb && dpkg -i /tmp/libsodium13_1.0.3-1~wheezy0_i386.deb
 - wget -O/tmp/libjson-c2_0.11-3~bpo7+1_i386.deb http://freifunk-pirmasens.de/libjson-c2_0.11-3~bpo7+1_i386.deb && dpkg -i /tmp/libjson-c2_0.11-3~bpo7+1_i386.deb
 - wget -O/tmp/libuecc0_6-0uf1_i386.deb http://freifunk-pirmasens.de/libuecc0_6-0uf1_i386.deb && dpkg -i /tmp/libuecc0_6-0uf1_i386.deb
 - wget -O/tmp/fastd-dbg_17-4_i386.deb http://freifunk-pirmasens.de/fastd-dbg_17-4_i386.deb && dpkg -i /tmp/fastd-dbg_17-4_i386.deb

script:
 - for f in * ; do echo "checking $f..."; fastd --verify-config --config-peer $f || exit 1; done
 - grep --no-filename "key" * | egrep -o "[0-9a-f]{60,80}" | sort | uniq -d > /tmp/peers-dubchecker
 - if [ -s /tmp/peers-dubchecker ]; then
     echo -e '\x1b[31mfound duplicate keys:\x1b[0m';
     cat /tmp/peers-dubchecker | while read i; do
       echo -n "$i (";
       grep -F "$i" -l -r . | egrep -o "[-_0-9a-zA-Z]{0,80}" | while read node; do
         echo -n "$node, ";
       done | head -c -2;
       echo ")";
     done;
     exit 1;
   else
     echo -e '\x1b[32mfound no duplicate keys\x1b[0m';
   fi

notifications:
  irc:
    channels:
      - "irc.hackint.org#ffwp"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
